---
version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/docs"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "weekly"
