---
# https://github.com/golangci/golangci-lint#config-file

run:
  timeout: 30m
  skip-files:
    - pkg/apis/snapscheduler/v1/zz_generated.openapi.go
output:
  sort-results: true
linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - goconst
    - gocyclo
    - goimports  # Supersedes gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
