---
# https://golangci-lint.run/usage/configuration/#config-file

run:
  allow-parallel-runners: true
  timeout: 10m
  # skip-files:
output:
  sort-results: true
linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - contextcheck
    - dupl
    - errcheck
    - errorlint
    - errname
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - goconst
    - gocyclo
    - goimports  # Supersedes gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
