---
# https://github.com/golangci/golangci-lint#config-file

run:
  timeout: 30m
  skip-files:
    - pkg/apis/snapscheduler/v1/zz_generated.openapi.go
linters:
  disable-all: true
  enable:
    - deadcode
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocyclo
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maligned
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
