---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datavol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: Pod
apiVersion: v1
metadata:
  name: workload
spec:
  containers:
    - name: workload
      image: gcr.io/distroless/static:debug-nonroot
      command: ["sh", "-c"]
      args: ["echo 'data' > /mnt/datafile; sleep 99999"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: true
        # seccompProfile:
        #   type: RuntimeDefault
      volumeMounts:
        - name: data
          mountPath: "/mnt"
  securityContext:
    runAsNonRoot: true
  terminationGracePeriodSeconds: 2
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: datavol
