---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 90
    script: |
      set -e -o pipefail

      echo "Waiting for snapshot"
      while [[ $(kubectl -n "$NAMESPACE" get volumesnapshots -oname) == '' ]]; do
        sleep 1
      done

      sname=$(kubectl -n "$NAMESPACE" get volumesnapshots -oname)

      echo "Verifying usage of custom snapshotclass"
      kubectl -n "$NAMESPACE" get $sname -otemplate='{{.spec.volumeSnapshotClassName}}' | grep -q 'my-custom-class'
