---
apiVersion: batch/v1
kind: Job
metadata:
  name: check-metrics
spec:
  template:
    spec:
      backoffLimit: 50
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args: ["wget -O- --no-check-certificate -q https://snapscheduler-metrics.backube-snapscheduler.svc.cluster.local:8443/metrics | grep 'workqueue_work_duration_seconds_count{name=\"snapshotschedule\"}'"]
      restartPolicy: Never
