---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datavol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
kind: Pod
apiVersion: v1
metadata:
  name: workload
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["echo 'data' > /mnt/datafile; sleep 99999"]
      volumeMounts:
        - name: data
          mountPath: "/mnt"
  terminationGracePeriodSeconds: 2
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: datavol
