---
apiVersion: v2
name: snapscheduler
# Chart version: Incremented during chart, template, or appVersion changes.
version: "1.2.1"
description: >-
    An operator to take scheduled snapshots of Kubernetes persistent volumes
type: application
# Adding "-0" at the end of the version string permits pre-release kube versions
# to match. See https://github.com/helm/helm/issues/6190
kubeVersion: "^1.13.0-0"
keywords:
  - csi
  - scheduler
  - snapshot
  - storage
home: https://backube.github.io/snapscheduler/
sources:
  - https://github.com/backube/snapscheduler
maintainers:
  - name: John Strunk
    email: jstrunk@redhat.com
    url: https://github.com/JohnStrunk
icon: https://raw.githubusercontent.com/backube/snapscheduler/master/docs/media/snapscheduler.svg?sanitize=true
# This is the version number of the application being deployed.
appVersion: "1.1.1"
