apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "snapscheduler.fullname" . }}
  labels:
    {{- include "snapscheduler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services  # metrics service
  - services/finalizers  # metrics?
  - configmaps  # For leader lock
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - {{ include "snapscheduler.fullname" . }}
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
# Operator has full control of its CRs
- apiGroups:
  - snapscheduler.backube
  resources:
  - '*'
  verbs:
  - '*'
# Operator has full control of snapshots
- apiGroups:
  - "snapshot.storage.k8s.io"
  resources:
  - volumesnapshots
  verbs:
  - '*'
# Operator must monitor PVCs to snapshot them
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
