---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 300
    script: |
      set -e -o pipefail

      echo "Waiting for snapshot"
      while [[ $(kubectl -n "$NAMESPACE" get volumesnapshots -oname) == '' ]]; do
        sleep 1
      done

      sname=$(kubectl -n "$NAMESPACE" get volumesnapshots -oname)

      echo "Waiting for snapshot to be ready: $sname"
      while [[ $(kubectl -n "$NAMESPACE" get "$sname" -otemplate="{{.status.readyToUse}}") != "true" ]]; do
        kubectl -n "$NAMESPACE" get "$sname"
        sleep 5
      done
