# permissions for end users to view snapshotschedules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snapshotschedule-viewer-role
rules:
- apiGroups:
  - snapscheduler.backube
  resources:
  - snapshotschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapscheduler.backube
  resources:
  - snapshotschedules/status
  verbs:
  - get
