---
apiVersion: snapscheduler.backube/v1alpha1
kind: SnapshotSchedule
metadata:
  name: example-hourly
spec:
  retention:
    # Snapshot expriation is a time.Duration and only supports up to hours
    expires: "168h"  # 1 week
    maxCount: 10
  # schedule fields: min hr dom mo dow
  schedule: "0 * * * *"
  snapshotTemplate:
    labels:
      mylabel: "myvalue"
    snapshotClassName: openshift-storage-ceph-rbd
