apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snapshotschedules.snapscheduler.backube
spec:
  group: snapscheduler.backube
  names:
    kind: SnapshotSchedule
    listKind: SnapshotScheduleList
    plural: snapshotschedules
    singular: snapshotschedule
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            claimSelector:
              description: ClaimSelector selects which PVCs will be snapshotted according
                to this schedule.
              type: object
            disabled:
              description: Disabled determines whether this schedule is currently
                disabled.
              type: boolean
            retention:
              properties:
                expires:
                  description: Expires is the length of time (time.Duration) after
                    which a given Snapshot will be deleted.
                  pattern: ^\d+(h|m|s)$
                  type: string
                maxCount:
                  format: int32
                  minimum: 1
                  type: integer
              type: object
            schedule:
              description: Schedule is a Cronspec specifying when snapshots should
                be taken.
              pattern: ^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){5}$
              type: string
            startDeadlineSeconds:
              description: StartDeadlineSeconds is the maximum number of seconds after
                the scheduled time when a snapshot is allowed to start.
              format: int32
              minimum: 1
              type: integer
            template:
              properties:
                hooks:
                  properties:
                    postSnapshot:
                      type: string
                    preSnapshot:
                      type: string
                  type: object
                labels:
                  additionalProperties:
                    type: string
                  type: object
              type: object
          type: object
        status:
          properties:
            lastSnapshotResult:
              description: LastSnapshotResult is the result of the last attempted
                set of snapshots.
              type: string
            lastSnapshotTime:
              description: LastSnapshotTime is the time of the most recent set of
                snapshots generated by this schedule.
              type: string
            nextSnapshotTime:
              description: NextSnapshotTime is the time when this schedule should
                create the next set of snapshots.
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
