---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: SnapScheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: SnapScheduler
  template:
    metadata:
      labels:
        name: SnapScheduler
    spec:
      serviceAccountName: SnapScheduler
      containers:
        - name: SnapScheduler
          # Replace this with the built image name
          image: quay.io/backube/snapscheduler
          command:
            - SnapScheduler
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "SnapScheduler"
