---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: snapscheduler
subjects:
- kind: ServiceAccount
  name: snapscheduler
roleRef:
  kind: Role
  name: snapscheduler
  apiGroup: rbac.authorization.k8s.io
