---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
ignore: |
  hack/crds/*
  helm/snapscheduler/templates/*
  helm/snapscheduler/crds/*
  config/**
rules:
  document-start:
    ignore: |
      deploy/olm-catalog/snapscheduler/1.1.1/snapshotschedules.snapscheduler.backube.crd.yaml
  indentation:
    indent-sequences: consistent
  line-length:
    allow-non-breakable-inline-mappings: true
    ignore: |
      deploy/olm-catalog/snapscheduler/1.1.1/snapshotschedules.snapscheduler.backube.crd.yaml
